Support get_config method and override required tests, add mock data …
napalm-automation-community/napalm-onyx pull request #7
Opened 2019-10-14 06:55 UTC by anas-shami

Support get_config method to fetch initial, running and candidate config. 
Add new tests one for testing 'all' and second one to fetch and validate initial and running data as an individual filter.

2019-10-14 06:55 UTC, anas-shami commented
@samerd  @anasbadaha  please review

2019-10-14 07:08 UTC, anasbadaha commented on napalm_onyx/onyx_ssh.py
>          raise NotImplementedError("get_config is not supported yet for onyx devices")
Please remove this line then add your code here!

2019-10-14 16:36 UTC, samerd commented
@anas-shami 
get_config should return the configuration as text not onyx json:
all other vendors are using: py23_compat.text_type(config.text)
please fix

2019-10-14 16:41 UTC, anas-shami commented
oh, its ok I'll use show commands, but in tests we have expected json file ! so I must return json for this method.

2019-10-14 16:53 UTC, samerd requested changes

2019-10-14 16:53 UTC, samerd commented on napalm_onyx/onyx_ssh.py
> +            command = 'show running-config | json-print'
```python
command = 'show running-config'
result = self._send_command(command)
config['running'] = py23_compat.text_type(result )
```

2019-10-15 10:59 UTC, anas-shami commented
I don't make a pull --rebase here this fails on py3.4  @samerd

2019-10-15 21:05 UTC, anas-shami commented
@samerd  could you please approve that so I can continue with other functions?

2019-10-15 21:32 UTC, samerd reviewed
Thanks @anas-shami 
seems great,
However it is still failing.
I suggest to work with a new updated clean branch

2019-10-16 18:55 UTC, closed without merging